# Generated by Django 2.1.7 on 2019-03-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190330_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
