# Generated by Django 2.1.7 on 2019-03-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190330_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.User')),
            ],
        ),
    ]
